// Copyright (c) 2017 Max Dietz. All rights reserved.
// Use of this source code is governed by a Apache-style license that can be
// found in the LICENSE file.
function provideAltText() {
    var imageNodes = document.getElementsByTagName("img");
    for (var img of imageNodes) {
        if (img.getAttribute('alt') == null || img.getAttribute('alt') == "") {
            generateAltText(img);
        }
    }
}

function visionResponseToString(data) {
    var response = data['responses'][0];
    if (response.hasOwnProperty('error')) {
        return "";
    }
    if (response.hasOwnProperty('labelAnnotations')) {
        var annotations = [];
        var maxAnnotation = null;
        for (var annotation of response['labelAnnotations']) {
            if (maxAnnotation == null || annotation['score'] > maxAnnotation['score']) {
                maxAnnotation = annotation;
            }
            if (annotation['score'] >= 0.95) {
                annotations.push(annotation);
            }
        }
        var string = "";
        if (annotations.length == 0 && maxAnnotation == null) {
            // There were no available label annotations. This is likely an
            // error and should never happen.
        } else if (annotations.length == 0) {
            string += "Autogenerated alt text: Image of likely a " + maxAnnotation['description'] +
                " confidence " + Math.round(maxAnnotation["score"] * 100) + "%.";
        } else {
            string += "Autogenerated alt text: Image looks like ";
            for (var annotation of annotations) {
                string += annotation['description'] + " ";
            }
        }
    }

    // Check for text being present.
    if (response.hasOwnProperty('textAnnotations') && response['textAnnotations'].length > 0) {
        string += ".  There is also text in this image, which reads ";
        for (var annotation in response['textAnnotations']) {
            string += annotation["description"];
        }
    }

    return string;
}

function generateAltText(img) {
    $.post({
        url: 'https://vision.googleapis.com/v1/images:annotate?key=AIzaSyBGs7TYQhunN9FqF16kfbV3yFxhthFsWrQ',
        data: JSON.stringify({
            "requests": [{
                "image": {
                    "source": {
                        "imageUri": img.src
                    },
                },
                "features": [{
                    "type": "TEXT_DETECTION"
                }, {
                    "type": "LABEL_DETECTION",
                    "maxResults": 3
                }]
            }]
        }),
        success: function(data) {
            img.setAttribute('alt', visionResponseToString(data));
        },
        dataType: "json",
        headers: {
            "Content-Type": "application/json",
        }
    });
}

$(document).ready(provideAltText);